@Wear.OS.Sync.Server_HostAddress = http://0.0.0.0

GET {{Wear.OS.Sync.Server_HostAddress}}/todos/
Accept: application/json

###

GET {{Wear.OS.Sync.Server_HostAddress}}/todos/1
Accept: application/json

###
